# Generated by Django 3.2 on 2023-11-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0002_car_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=255)),
                ('entry_time', models.DateTimeField(verbose_name='entry time')),
                ('out_time', models.DateTimeField(verbose_name='out time')),
            ],
        ),
        migrations.CreateModel(
            name='OutTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=255)),
                ('entry_time', models.DateTimeField(verbose_name='entry time')),
                ('out_time', models.DateTimeField(verbose_name='out time')),
            ],
        ),
        migrations.CreateModel(
            name='TableComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=255)),
                ('entry_time', models.DateTimeField(verbose_name='entry time')),
                ('out_time', models.DateTimeField(verbose_name='out time')),
            ],
        ),
    ]
