# Generated by Django 3.2 on 2023-11-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0003_entrytable_outtable_tablecomplet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytable',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='out time'),
        ),
        migrations.AlterField(
            model_name='outtable',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='out time'),
        ),
        migrations.AlterField(
            model_name='tablecomplet',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='out time'),
        ),
    ]
